config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :albums do
    patch "program"
    post "add_track"
    get "new_track"
    get "tracks"
    collection do 
      get "programmed"
    end
  end
  resources :graph
  get 'welcome/index'

  root 'welcome#index'
  get 'help' => 'welcome#help'

end

app/models/album.rb
class Album < ActiveRecord::Base
has_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all.where(:programmed => false)
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  def tracks
    @album = Album.find(params[:album_id])
    @tracks = @album.tracks.all
    @album_title = @tracks.first.album.albumTitle
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_path, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def programmed
    @albums = Album.all.where(:programmed => true)
  end

  # POST /albums/id/programmed
  def program
    @album = Album.find(params[:album_id])
    respond_to do |format|
      if @album.update(:programmed => true)
        format.html { redirect_to album_new_track_path(@album.id), notice: 'Album was successfully programmed.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :index }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end  
  end

  def add_track
      @album = Album.find(params[:album_id])
  end

  def new_track
      @album = Album.find(params[:album_id])
      @track = @album.tracks.new
      @track.artist = @album.artist
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:mediaType, :recordLabel, :albumTitle, :artist, :recordingYear, :spotify, :notes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  #render :json => @@data
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        puts @track.album_id
        format.html { redirect_to album_tracks_path(@track.album_id), notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to album_tracks_path(@track.album_id), notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to album_tracks_path(@track.album_id), notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :artist, :format, :explicit, :automation, :frequency, :album_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    
    <div class"row">
      <div class="col-xs-3">
        <div id="sidebar">
      <ul class="list-group">
       <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
      </ul>
    </div>
      </div>
      <div class="col-xs-9">
        <div class="field form-group">
          <%= f.label :mediaType, 'Media Type' %><br>
          <%= f.text_field :mediaType %>
        </div>
        <div class="field form-group">
          <%= f.label :recordLabel, 'Record Label' %><br>
          <%= f.text_field :recordLabel %>
        </div>
        <div class="field form-group">
          <%= f.label :albumTitle, 'Album Title' %><br>
          <%= f.text_field :albumTitle %>
        </div>
        <div class="field form-group">
          <%= f.label :artist, 'Artist' %><br>
          <%= f.text_field :artist %>
        </div>
        <div class="field form-group">
          <%= f.label :recordingYear, 'Recording Year' %><br>
          <%= f.number_field :recordingYear %>
        </div>
        <div class="field form-group">
          <%= f.label :spotify, 'Spotify' %><br>
          <%= f.url_field :spotify %>
        </div>
        <div class="field form-group">
          <%= f.label :notes, 'Notes' %><br>
          <%= f.text_field :notes %>
        </div>
      <div class="actions">
        <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/index.html.erb
<div id="notice" class="<%= 'alert alert-success' if notice != nil %>" role="alert"><%= notice %></div>

<!-- <div class="row"> 
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    
</div>
</div> -->

<div class="container">
  <h1 id="title1">Incoming Albums</h1>
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
        </ul>
    </div>
  </div>

      <!-- table -->
  <div id="albums" class="col-xs-9 col-sm-9 col-md-9 col-lg-4">
      <input type="text" style="width:200px;" class="search form-control" placeholder="Search for..."/>
      <table class="table table-bordered table-hover table-responsive">
        <thead>
        </br>
          <tr>
            <th>Media Type</th>
            <th>Record Label</th>
            <th>Album Title</th>
            <th>Artist</th>
            <th>Recording Year</th>
            <th>Spotify</th>
            <th>Notes</th>
            <th>Program</th>
            <th>Edit</th>
            <th>Reject</th>
          </tr>
        </thead>
        <div class="row">
          <tbody class="list">
            <% @albums.each do |album| %>
            <tr>
              <td><%= album.mediaType %></td>
              <td class="recordlabel"><%= album.recordLabel %></td>
              <td class="albumtitle"><%= album.albumTitle %></td>
              <td class="artist"><%= album.artist %></td>
              <td><%= album.recordingYear %></td>
              <td><a href=<%= album.spotify %>>Listen Here!</a></td>
              <td><%= album.notes %></td>
              <td><%= button_to "Program", album_program_path(album), :method => :patch %>
              </td>
              <td><%= link_to 'Edit', edit_album_path(album) %></td>
              <td><%= link_to 'Reject', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </div>
      </table>
      <script type="text/javascript">
        var options = {
          valueNames: [ 'artist' , 'albumtitle' , 'recordlabel']
        };

        var userList = new List('albums', options);
      </script>
  </div> 
</div>
</div>

app/views/albums/new_track.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container">
    <h1>New Track</h1>
    <div class"row">
      <div class="col-xs-3">
        <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
      </ul>
    </div>
      </div>
      <div class="col-xs-9">
        <div class="field form-group">
          <%= f.label :number, 'Track Number' %><br>
          <%= f.text_field :number %>
        </div>
        <div class="field form-group">
          <%= f.label :side, 'CD Side' %><br>
          <%= f.text_field :side %>
        </div>
        <div class="field form-group">
          <%= f.label :name, 'Name' %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field form-group">
          <%= f.label :artist, 'Artist' %><br>
          <%= f.text_field :artist %>
        </div>
        <div class="field form-group">
          <%= f.label :format, 'Format' %><br>
          <%= f.text_field :format %>
        </div>
        <div class="field form-group">
          <%= f.label :explicit, 'Explicit' %><br>
          <%= f.check_box :explicit %>
        </div>
        <div class="field form-group">
          <%= f.label :automation, 'Automation' %><br>
          <%= f.check_box :automation %>
        </div>
        <div class="field form-group">
          <%= f.label :frequency, 'Frequency' %><br>
          <%= f.text_field :frequency %>
        </div>
      <div class="actions">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
      </br>
      
      </div>
    </div>
  </div>
<%end%>

app/views/albums/programmed.html.erb
<p id="notice"><%= notice %></p>

<!-- <div class="row"> 
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    
</div>
</div> -->

<div class="container">
  <h1 id="title1">Programmed Albums</h1>
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
        </ul>
    </div>
  </div>

      <!-- table -->
  <div id="albums" class="col-xs-9 col-sm-9 col-md-9 col-lg-4">
      <input type="text" style="width:200px;" class="search form-control" placeholder="Search for..."/>
      <table class="table table-bordered table-hover table-responsive">
        <thead>
        </br>
          <tr>
            <th>Media Type</th>
            <th>Record Label</th>
            <th>Album Title</th>
            <th>Artist</th>
            <th>Recording Year</th>
            <th>Spotify</th>
            <th>Notes</th>
            <th>New Tracks</th>
            <th>View Track</th>
            <th>Edit</th>
            <th>Reject</th>
          </tr>
        </thead>
        <div class="row">
          <tbody class="list">
            <% @albums.each do |album| %>
            <tr>
              <td><%= album.mediaType %></td>
              <td class="recordlabel"><%= album.recordLabel %></td>
              <td class="albumtitle"><%= album.albumTitle %></td>
              <td class="artist"><%= album.artist %></td>
              <td><%= album.recordingYear %></td>
              <td><a href=<%= album.spotify %>>Listen Here!</a></td>
              <td><%= album.notes %></td>
              <td><%= link_to 'New Tracks', album_new_track_path(album.id) %></td>
              <td><%= link_to 'View Tracks', album_tracks_path(album.id) %></td>
              <td><%= link_to 'Edit', edit_album_path(album) %></td>
              <td><%= link_to 'Reject', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </div>
      </table>
      <script type="text/javascript">
        var options = {
          valueNames: [ 'artist' , 'albumtitle' , 'recordlabel']
        };

        var userList = new List('albums', options);
      </script>
  </div> 
</div>
</div>

app/views/albums/tracks.html.erb
<div id="notice" class="<%= 'alert alert-success' if notice != nil %>" role="alert"><%= notice %></div>


<div class="container">
  <h1><%= @album.albumTitle %></h1>
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                Help
          </li>
        </ul>
    </div>
  </div>

      <!-- table -->
  <div id="tracks" class="col-xs-9 col-sm-9 col-md-9 col-lg-4">
      <input type="text" style="width:200px;" class="search form-control" placeholder="Search for..."/>
      <table class="table table-bordered table-hover table-responsive">
        <thead>
        </br>
          <tr>
<!--             <th>Album Title</th> -->
<!--             <th>Artist</th> -->
            <th>Track Number</th>
            <th>CD Side</th>
            <th>Track Title</th>
            <th>Format</th>
            <th>Explicit</th>
            <th>Automation</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <div class="row">
          <tbody class="list" style="table-layout: fixed">
            <% @tracks.each do |track| %>
            <tr>
              <td><%= track.number %></td>
              <td><%= track.side %></td>
              <td><%= track.name %></td>
              <td><%= track.format %></td>
              </td>
              <td><%= 
                if track.explicit 
                  "Yes" 
                else 
                  "No" 
                end
                %></td>
              </td>
              <td><%= 
                if track.automation 
                  "Yes" 
                else 
                  "No" 
                end
                %></td>
              </td>
              <td><%= link_to 'Edit', edit_track_path(track) %></td>
              <td><%= link_to 'Delete', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </div>
      </table>
      <script type="text/javascript">
        var options = {
          valueNames: [ 'tracktitle' , 'format']
        };

        var userList = new List('tracks', options);
      </script>
  </div> 
</div>
</div>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    
    <div class"row">
      <div class="col-xs-3">
        <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
      </ul>
    </div>
      </div>
      <div class="col-xs-9">
        <div class="field form-group">
          <%= f.label :name, 'Name' %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field form-group">
          <%= f.label :artist, 'Artist' %><br>
          <%= f.text_field :artist %>
          <%= f.text_field :artist %>
        </div>
        <div class="field form-group">
          <%= f.label :format, 'Format' %><br>
          <%= f.text_field :format %>
        </div>
        <div class="field form-group">
          <%= f.label :explicit, 'Explicit' %><br>
          <%= f.check_box :explicit %>
        </div>
        <div class="field form-group">
          <%= f.label :automation, 'Automation' %><br>
          <%= f.check_box :automation %>
        </div>
        <div class="field form-group">
          <%= f.label :frequency, 'Frequency' %><br>
          <%= f.text_field :frequency %>
        </div>
        <div class="field form-group">
          <%= f.label :album_id, 'Album ID' %><br>
          <%= f.text_field :album_id %>
        </div>
      <div class="actions">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
      </br>
      
      </div>
    </div>
  </div><br>
<%end%>

app/views/tracks/edit.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container">
    <h1>Editing Track</h1>
    <div class"row">
      <div class="col-xs-3">
        <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
      </ul>
    </div>
      </div>
      <div class="col-xs-9">
        <div class="field form-group">
          <%= f.label :number, 'Track Number' %><br>
          <%= f.text_field :number %>
        </div>
        <div class="field form-group">
          <%= f.label :side, 'CD Side' %><br>
          <%= f.text_field :side %>
        </div>
        <div class="field form-group">
          <%= f.label :name, 'Name' %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field form-group">
          <%= f.label :artist, 'Artist' %><br>
          <%= f.text_field :artist %>
        </div>
        <div class="field form-group">
          <%= f.label :format, 'Format' %><br>
          <%= f.text_field :format %>
        </div>
        <div class="field form-group">
          <%= f.label :explicit, 'Explicit' %><br>
          <%= f.check_box :explicit %>
        </div>
        <div class="field form-group">
          <%= f.label :automation, 'Automation' %><br>
          <%= f.check_box :automation %>
        </div>
        <div class="field form-group">
          <%= f.label :frequency, 'Frequency' %><br>
          <%= f.text_field :frequency %>
        </div>
      <div class="actions">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
      </br>
      
      </div>
    </div>
  </div>
<%end%>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  
<div class="row">
  <h1 style="padding-left: 6.5%">New Track</h1>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <span class="badge">8</span>
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
        </ul>
    </div>
  </div>

      <!-- table -->
  <div class="col-xs-9 col-sm-9 col-md-9 col-lg-4">
      <table class="table table-bordered table-hover table-responsive">
        <thead>
          <tr>
            <thead>
              <tr>
                <th>Name</th>
                <th>Artist</th>
                <th>Format</th>
                <th>Explicit</th>
                <th>Automation</th>
                <th>Frequency</th>
                <th>Album</th>
                <th colspan="3"></th>
              </tr>
            </thead>
        </thead>
        <div class="row">
          <tbody>
            <% @tracks.each do |track| %>
              <tr>
                <td><%= track.name %></td>
                <td><%= track.artist %></td>
                <td><%= track.format %></td>
                <td><%= track.explicit %></td>
                <td><%= track.automation %></td>
                <td><%= track.frequency %></td>
                <td><%= track.album %></td>
                <td><%= link_to 'Show', track %></td>
                <td><%= link_to 'Edit', edit_track_path(track) %></td>
                <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </div>
      </table>
  </div> 
</div>
</div>
<br>

<%= link_to 'New Track', new_track_path %>

app/views/welcome/help.html.erb
<div id="notice" class="<%= 'alert alert-success' if notice != nil %>" role="alert"><%= notice %></div>

<!-- <div class="row"> 
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    
</div>
</div> -->

<div class="container">
  <h1 id="title1">Help</h1>
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div id="sidebar">
      <ul class="list-group">
        <li class="list-group-item">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Add An Album', new_album_path %>
          </li>
          <li class="list-group-item">
            <!-- <span class="badge">8</span> -->
            <%= link_to 'Incoming Albums', albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Programmed Albums', programmed_albums_path %>
          </li>
          <li class="list-group-item">
                <%= link_to 'Help', help_path %>
          </li>
        </ul>
    </div>
  </div>
    <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
      <h2> Frequently Asked Questions</h2>
      <h3> 1. How do I add an album? </h3>
      <h4>Simply select the "Add an Album" option from the side menu. Once selected, you can fill out all of the information that is found on the potential album.</h4>
      </br>
      <h3> 2. How do I edit an album? </h3>
      <h4>Once in the "Incoming albums" or "Programmed albums" section, select the "Edit Album" option from the album row that you wish to edit. Once you finish editing your album, click submit and you're ready to go!</h4>
      </br>
      <h3> 3. How do I reject an album? </h3>
      <h4>Once in the "Incoming albums" or "Programmed albums" section, select the "Reject" option from the album row that you wish to reject.</h4>
      </br>
      <h3> 4. How do I program an album? </h3>
      <h4>Once in the "Incoming albums" section, select the "Program" option from the album row that you wish to program.</h4>
      </br>
      <h3> 5. How do I add tracks to an album? </h3>
      <h4>Once an album has been programmed, you can add tracks by navigating to the "Programmed Albums" menu option and then the "Add Tracks" option for the album you wish to add tracks to.</h4>
      </br>
      <h3> 6. How do I edit a track </h3>
      <h4>Once in the "Programmed albums" section, select the "Edit Track" option from the track row that you wish to edit. Once you finish editing your track, click submit and you're ready to go!</h4>
      </br>
      <h3> 7. What is the frequency of an album/track? </h3>
      <h4>Frequency refers to the amount of airplay that particular album/track will receive. 0 refers to low, 1 refer to medium, and 2 refers to high. </h4>
      </br>
      <h3> 8. Have more questions? </h3>
      <h4>Email <u><a href="mailto:it.director@wrek.org">it.director@wrek.org</a></u></h4>
      </br>
    </div>
</div>
</div>